---
- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: present

- name: Verify pip3 installation
  shell: pip3 --version
  register: pip_check
  changed_when: false
  failed_when: pip_check.rc != 0
