---
- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Verify Docker Compose installation
  shell: docker-compose --version
  register: compose_check
  changed_when: false
  failed_when: compose_check.rc != 0
