---
- name: Download and install Go
  shell: |
    curl -LO https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz
    rm -rf /usr/local/go
    tar -C /usr/local -xzf go{{ go_version }}.linux-amd64.tar.gz
  args:
    creates: /usr/local/go/bin/go

- name: Add Go to system PATH
  lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:/usr/local/go/bin'
    state: present

- name: Verify Go installation
  shell: /usr/local/go/bin/go version
  register: go_check
  changed_when: false
  failed_when: go_check.rc != 0
