- name: Update package cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install EPEL (CentOS)
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"
