---
- name: Ensure apt keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: ansible_os_family == "Debian"

- name: Download Docker GPG key to keyrings
  get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  when: ansible_os_family == "Debian"

- name: Remove legacy Docker repo if exists
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent
  when: ansible_os_family == "Debian"

- name: Add Docker repository with Signed-By
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
  when: ansible_os_family == "Debian"

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Docker CE
  apt:
    name: "docker-ce{{ ('=' + docker_version) if docker_version | length > 0 else '' }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure Docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: true

- name: Add current user to docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes


